name: auto-WIW

on:
  schedule:
    - cron: '1 12 * * 5'  # Schedule every Friday at 13:01 CET

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Claim open shifts
        run: node index.js

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with: 
          name: logs
          path: activity.log
